General:
    MODEL_NAME: MAX_MIL
    seed: 2024
    num_classes: 4
    num_epochs: 50
    device: 1
    num_workers: 4
    best_model_metric: val_auc  # val_auc or val_acc val_f1 val_loss val_recall val_precision
    earlystop: 
        use: False
        patience: 5
        metric: val_auc  # val_auc or val_acc val_f1 val_loss val_recall val_pre

Dataset:
    DATASET_NAME: CAMELYON17_4CLS
    dataset_csv_path: /data_sda/lxt/CAMELYON_BENCHMARK/datasets/CAMELYON17_4CLS_PLIP.csv
    VIST: True

Logs:
    log_root_dir: /data_sda/lxt/CAMELYON_BENCHMARK/logs

Model:
    in_dim: 512
    dropout: 0.1
    act: relu  # relu or silu gule
    optimizer:
        which: adam    # adam or adamw
        adam_config:
            lr: 0.0002
            weight_decay: 0.00001
        adamw_config:
            lr: 0.0002
            weight_decay: 0.00001
    criterion: ce  # ce
    scheduler:
        which: step  # step_lr or plateau cosine none
        step_config:
            step_size: 10
            gamma: 0.1

        

    
     