General:
    MODEL_NAME: RRT_MIL
    seed: 2024
    num_classes: 4
    num_epochs: 50
    device: 2
    num_workers: 4
    best_model_metric: val_auc  # val_auc or val_acc val_f1 val_loss val_recall val_precision
    earlystop: 
        use: False
        patience: 5
        metric: val_auc  # val_auc or val_acc val_f1 val_loss val_recall val_pre

Dataset:
    DATASET_NAME: GEM_2CLS
    # to use train-val-test, open  dataset_csv_dir
    # to use k-fold cross validation, open  dataset_csv_path
    
    # dataset_csv_path: /data_sda/lxt/CAMELYON_BENCHMARK/datasets/CAMELYON17_4CLS_PLIP.csv
    dataset_root_dir: /data_sdd/lxt/GEM_MIL/MIL_BASELINE/datasets_csv/GEM-2cls
    VIST: True

Logs:
    log_root_dir: /data_sdd/lxt/GEM_MIL/MIL_BASELINE/logs

Model:
    in_dim: 512
    act: 'relu'
    region_num: 8
    pos: 'none'
    pos_pos: 0
    pool: 'cls_token'
    peg_k: 7
    drop_path: 0
    n_layers: 1
    n_heads: 8
    attn: 'rrt'
    da_act: 'tanh'
    trans_dropout: 0.1
    ffn: False
    mlp_ratio: 4.
    trans_dim: 64
    epeg: True
    min_region_num: 0
    qkv_bias: True
    conv_k: 15
    conv_2d: False
    conv_bias: True
    conv_type: 'attn'
    region_attn: 'native'
    dropout: 0.1
    act: relu  # relu or silu gule
    optimizer:
        which: adam    # adam or adamw
        adam_config:
            lr: 0.0002
            weight_decay: 0.00001
        adamw_config:
            lr: 0.0002
            weight_decay: 0.00001
    criterion: ce  # ce
    scheduler:
        which: step  # step_lr or plateau cosine none
        step_config:
            step_size: 10
            gamma: 0.1

        

    
     